In [ ]:
# 4 types :

# 1) position

# 2) keyword

# 3) default

# 4) variable-length

In [ ]:
#                                                                   1) Position Argument:

# It will be Assigning (Based on positions)

# Examples : 1

def person(name, age):

  print("Name : ", name)
  print("Age : ", age)

person("Hari", 24)

Name :  Hari
Age :  24

In [ ]:
# # Examples : 2

# def person(name, age):

#   print("Name : ", name)
#   print("Age : ", age+2)


# person(24, "Hari")      # Gives ...>  Type Error : can only concatenate str (not "int") to str

In [ ]:
#                                                                        2) keyword Argument

# Example - 1:

def person(name, age):

  print("Name : ", name)
  print("Age : ", age)

person(age = 24, name = "Yogesh")

Name :  Yogesh
Age :  24

In [ ]:
# #                                                                        3) default Argument


# # Non-default argument follows "Default arguments"

# # Examples :

# def person(name="Hari", age):

#   print("Name : ", name)
#   print("Age : ", age)

# person(24)    # SyntaxError: non-default argument follows default argument

In [ ]:
# Fix the Above error

def person(age, name="Hari"):

  print("Name : ", name)
  print("Age : ", age)

person(24)

Name :  Hari
Age :  24

In [ ]:
#                                                                            4) Variable-length Arguments

#  Examples :

def add(x, *y):

  print("x = ", x)
  print("y = ", y)

  z = x + y

  print("Sum = ", z)


add(10,20,30,40)

x =  10
y =  (20, 30, 40)

TypeError: unsupported operand type(s) for +: 'int' and 'tuple'

In [ ]:
# Fix the Above code error


def add(x, *y):

  print("x = ", x)
  print("y = ", y)


  z = x

  for i in y:

    z = z + i

  print("Sum = ", z)


add(10,20,30,40)

x =  10
y =  (20, 30, 40)
Sum =  100

In [3]:
# Keyword aarguments (**kwargs)

# Examples:

def person(name, **values):

  print("Name : ", name)

  print("Values : ", values.items())


  for i, j in values.items():

    print(i," : ", j)


# Call the Function

person("Hari", age=24, city="Chennai", mailId="hariyogeshram882@gmail.com")

Name :  Hari
Values :  dict_items([('age', 24), ('city', 'Chennai'), ('mailId', 'hariyogeshram882@gmail.com')])
age  :  24
city  :  Chennai
mailId  :  hariyogeshram882@gmail.com